---
abstract: 'Encode/Decode Values In A Structure'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  JSON: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.2.0, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Recursive-Encode
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Data::Recursive::Encode:
    file: lib/Data/Recursive/Encode.pm
    version: '0.06'
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/tokuhirom/p5-data-recursive-encode/issues
  homepage: https://github.com/tokuhirom/p5-data-recursive-encode
  repository: git://github.com/tokuhirom/p5-data-recursive-encode.git
version: '0.06'
x_contributors:
  - 'gfx <gfuji@cpan.org>'
  - 'Hiroki Honda <cside.story@gmail.com>'
  - 'Hiroyoshi Houchi <git@hixi-hyi.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
